safe:        false
auto:        false
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
permalink:   date

exclude: Gemfile, Gemfile.lock, README.md, config.ru

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

markdown: redcarpet2
redcarpet:
  extensions: ["fenced_code_blocks"]